name: Check Partnership Updates

on:
  push:
    paths:
      - 'data/quantum-partnerships.csv'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for new partnerships
        run: |
          echo "Partnership CSV updated!"
          # Could send notification or trigger other actions